# The URL the site will be built for
base_url = "https://r6.technology/"
theme = "hacker"

# The title of the site
title = "r6.technology"

# The description of the site
description = "Hey check this out"

author = "Ryan Cast"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to minify the HTML when building the site
minify_html = false

# Whether to generate an Atom feed
generate_feeds = true

# Taxonomies
taxonomies = [{ name = "tags" }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "charcoal"

# Whether to render emojis
render_emoji = true

# Whether footnotes are rendered in the GitHub-style (at the bottom, with back references) or plain (in the place, where they are defined)
bottom_footnotes = true

[extra]
title_separator = "|" # set as |, -, _, etc

# The path to the logo of the site
logo = "images/logo.png"

# Google Analytics tracking ID
# google_analytics = "example-tracking-id"

# Contact form script id that points to google macros (e.g. https://script.google.com/macros/s/<script-identifier>/exec)
contact_form_script_id = "<script-identifier>"

# Visitor notifier based on IFTTT + Webhooks. Sample here - /assets/js/monitor.js
monitor = false

# Menu items
menu = [{ url = "/tags", name = "Tags" }]

language_code = "en-US"

# Enable OpenGraph metadata
opengraph = true

timezone = "UTC"
# timeformat = ""

# The path to cv file if you use cv shortcode
# cv_file = "/files/Curriculum_Vitae.pdf"

# provide link to edit page on github
edit_page = true

# Use theme specific tags page based on templates/tags.html
simplified_tags = false

# Social links
social_links = [
  { platform = "email", user_id = "web@ryancast.com" },
  { platform = "github", user_id = "r6t" },
  # { platform = "linkedin", user_id = "johndoe" },
  { platform = "feed", user_id = true },
  # { platform = "keyoxide", user_id = "aspe:host:XXXXXXX" },
  # { platform = "facebook", user_id = "" },
  # { platform = "instagram", user_id = "" },
  # { platform = "pinterest", user_id = "" },
  # { platform = "twitter", user_id = "" },
  # { platform = "stackoverflow", user_id = "" },
  # { platform = "youtube", user_id = "" },
  # { platform = "telegram", user_id = "" },
]

# GitHub settings that are used to generate the edit page link
[extra.github]
username = "r6t"
repo = "r6-technology-site"

# Giscus settings
[extra.giscus]
repo = "en9inerd/zola-hacker"
repo_id = "R_kgDONMlyug"
category = "Comments"
category_id = "DIC_kwDONMlyus4Ck_Vx"
mapping = "og:title"
strict = 0
reactions_enabled = 1
emit_metadata = 0
input_position = "top"
theme = "dark"
lang = "en"
loading = "lazy"
crossorigin = "anonymous"

# JSON-LD metadata
[extra.bio]
gender = "male"
employer_name = "Cloudcast"
employer_url = "https://cloudcast.consulting"
job_title = "Cloud Engineer"
links = [
  "https://github.com/r6t",
]
